import os
import time
import re
from google import genai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

SYSTEM_PROMPT = """You are an expert secretary.
Your task is to summarize the provided meeting transcript into structured meeting minutes.
The transcript may have some errors as it is generated by AI speech-to-text.

Please output the minutes in the following Markdown format:

# Meeting Minutes

## Key Points
- (Bulleted list of important topics discussed)

## Action Items
- [ ] (Task) - (Assignee if known)

## Summary
(A concise paragraph summarizing the meeting)
"""

def summarize_with_gemini(transcript: str) -> str:
    """
    Summarizes the transcript using Gemini 1.5 Flash.
    Includes retry logic for rate limits.
    """
    if not GEMINI_API_KEY:
        raise ValueError("GEMINI_API_KEY is not set. Please check your .env file.")

    client = genai.Client(api_key=GEMINI_API_KEY)
    
    # Retry configuration
    max_retries = 3
    base_delay = 2.0

    prompt = f"{SYSTEM_PROMPT}\n\nTranscript:\n{transcript}"

    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model="gemini-1.5-flash",
                contents=prompt
            )
            return response.text
        
        except Exception as e:
            # Check for rate limit (429) or other transient errors
            error_msg = str(e)
            print(f"Attempt {attempt+1} failed: {error_msg}")
            
            if attempt < max_retries - 1:
                # Simple exponential backoff or use retry-after hint if available
                wait_time = base_delay * (2 ** attempt)
                print(f"Retrying in {wait_time} seconds...")
                time.sleep(wait_time)
            else:
                raise RuntimeError(f"Failed to generate summary after {max_retries} attempts: {error_msg}")

    return ""
